### ISSUE TITLE
3d print files

### ISSUE THREAD

**Issue by msrahmanian** [python-friends/auto-scope#10]
Hello
Thank you so much for sharing this project, I 'd like to ask for 3d print files and hardware specifications, is it possible to share with us?
Thanks alot

**Comment by Wytamma** [comment]
No worries @msrahmanian happy to share :) 

The 3D files are available via thingiverse (https://www.thingiverse.com/thing:3182595).

I've updated the README with this information (b13b59b6c2dd447dac06d45f172f7731f2976e05)
